services:
  web:
    image: odoo:18
    depends_on:
      - db
    ports:
      - "8060:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - .:/mnt/extra-addons/smart_farm
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    volumes:
      - odoo-db-data:/var/lib/postgresql/data

volumes:
  odoo-web-data:
  odoo-db-data:
